project:
  type: website
  output-dir: docs

website:
  navbar:
    left:
    - text: "Aman Arora's Blog"
      href: index.qmd    
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
format:
  html:
    theme: cosmo